nelmio_api_doc:
    documentation:
        info:
            title: img-snap API
            description: Image Proxy & Management Dashboard API
            version: 1.0.0
        components:
            securitySchemes:
                ApiKeyAuth:
                    type: apiKey
                    in: header
                    name: X-AUTH-TOKEN
        security:
            - ApiKeyAuth: []
    areas:
        path_patterns:
            - ^/image
            - ^/store
